import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import { Nunito } from "@next/font/google";

const fontNunito = Nunito({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-dvh ${fontNunito.variable}`}>
        <Header />
        <main className="flex-grow"> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
