import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-dvh">
        <Header />
        <main className="flex-grow"> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
