import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import { Nunito } from "@next/font/google";

const fontNunito = Nunito({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex min-h-dvh flex-col ${fontNunito.variable}`}>
        <Header />
        <main className="relative flex-grow">
          {/* Background Image with Opacity */}
          <div
            className="absolute inset-0 -z-10 bg-[url('/assets/background.webp')]"
            style={{
              backgroundSize: "cover", // Resmi ekranı dolduracak şekilde ayarla
              backgroundAttachment: "fixed", // Kaydırıldığında sabit kalır
              backgroundPosition: "center", // Ortala
              backgroundRepeat: "no-repeat", // Tekrarlamayı kaldır
              opacity: 0.5, // Opaklığı düşür
            }}
          ></div>
          {/* Main Content */}
          <div className="relative z-10">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}


// import Header from "@/components/Header";
// import "./globals.css";
// import Footer from "@/components/Footer";
// import { Nunito } from "@next/font/google";

// const fontNunito = Nunito({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`flex min-h-dvh flex-col ${fontNunito.variable} bg-opacity-50 bg-[url('/assets/background.webp')] bg-repeat`}
//         style={{
//           backgroundSize: "auto",
//           backgroundAttachment: "fixed", // Arka planın kaydırılmaması için
//           backgroundPosition: "center top",
//         }}
//       >
//         <Header />
//         <main className="relative flex-grow">
//           {/* Main Content */}
//           <div className="relative z-10">{children}</div>
//         </main>
//         <Footer />
//       </body>
//     </html>
//   );
// }

// import Header from "@/components/Header";
// import "./globals.css";
// import Footer from "@/components/Footer";
// import { Nunito } from "@next/font/google";

// const fontNunito = Nunito({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`flex min-h-dvh flex-col ${fontNunito.variable}`}>
//         <Header />
//         <main className="relative flex-grow">
//           {/* Background Image */}
//           <div className="absolute inset-0 -z-10">
//             <img
//               src="/assets/background.webp"
//               alt=""
//               className="pointer-events-none h-full w-full object-cover opacity-50"
//             />
//           </div>
//           {/* Main Content */}
//           <div className="relative z-10">{children}</div>
//         </main>

//         <Footer />
//       </body>
//     </html>
//   );
// }
