import { ProductCard } from "@/components/ProductCard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <ProductCard />
    </>
  );
}
